name: MacOS

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    if: ${{ false }} # This job is temporarily disabled
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event_name == 'pull_request_target' && github.event.pull_request.head.sha || github.ref }}
    - uses: actions/setup-go@v5
      with:
        go-version-file: go.mod
    - name: brew
      run: |
        brew config
        brew update && (brew list cmake || brew install cmake)
        brew tap viamrobotics/brews
        brew install pkg-config
        brew install nlopt-static
        brew install x264
    - name: build
      run: go build ./web/cmd/server
    - uses: actions/upload-artifact@v4
      with:
        name: viam-server-macos
        path: server
        retention-days: 5
