name: MacOS

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event_name == 'pull_request_target' && github.event.pull_request.head.sha || github.ref }}
    - uses: actions/setup-go@v5
      with:
        go-version: '1.21.x'

    - name: config + tap
      run: |
        brew config
        # note: this must come before caching because we use it to invalidate
        brew tap viamrobotics/brews
    # note: this caching is brittle but we are okay with periodic build failures in exchange for speed
    # TODO(RSDK-5474): replace with bottling
    - id: cache-brew
      uses: actions/cache@v4
      with:
        path: |
          /usr/local/**/tensorflow*
          /usr/local/**/nlopt*
        key: ${{ hashFiles('/usr/local/Homebrew/Library/Taps/viamrobotics/homebrew-brews/**/*', '.github/workflows/macos.yml') }} }}
    - name: brew
      run: |
        brew tap viamrobotics/brews
        brew install pkg-config
        brew install nlopt-static
        brew install x264
        brew install jpeg-turbo
        brew install ffmpeg
        brew install tensorflowlite # Needs to be last

    - name: build
      run: go build ./web/cmd/server
    - uses: actions/upload-artifact@v3
      with:
        name: viam-server-macos
        path: server
        retention-days: 5
