name: MacOS

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event == 'pull_request_target' && github.event.pull_request.head.sha || github.ref }}
    - uses: actions/setup-go@v4
      with:
        go-version: '1.19.x'
    - name: brew
      run: |
        brew tap viamrobotics/brews
        brew install pkg-config
        brew install nlopt-static
        brew install x264
        brew install jpeg-turbo
        brew install ffmpeg
        brew install tensorflowlite # Needs to be last
    - name: build
      run: go build ./web/cmd/server
    - uses: actions/upload-artifact@v3
      with:
        name: viam-server-macos
        path: server
