name: Main Branch Update

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches: [ 'main', 'smurf-workflow' ]
    paths-ignore:
      - 'README.md'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

# To test workflow updates you need to work in a branch directly on viamrobotics/rdk
# and tag your working branch instead of @main in any viamrobotics/rdk "uses" below.
# Don't forget to tag back to @main before merge.

jobs:
  test:
    uses: viamrobotics/rdk/.github/workflows/test.yml@smurf-workflow
    secrets:
      REPO_READ_TOKEN: ${{ secrets.REPO_READ_TOKEN }}
      GIT_ACCESS_TOKEN: ${{ secrets.GIT_ACCESS_TOKEN }}

  appimage:
    needs: test
    uses: viamrobotics/rdk/.github/workflows/appimage.yml@smurf-workflow
    secrets:
      GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
      REPO_READ_TOKEN: ${{ secrets.REPO_READ_TOKEN }}
