name: Build and Publish Latest

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'

# To test workflow updates you need to work in a branch directly on viamrobotics/rdk
# and tag your working branch instead of @main in any viamrobotics/rdk "uses" below.
# Don't forget to tag back to @main before merge.

jobs:
  test:
    uses: viamrobotics/rdk/.github/workflows/test.yml@test-workflow
    secrets:
      MONGODB_TEST_OUTPUT_URI: ${{ secrets.MONGODB_TEST_OUTPUT_URI }}
      DOCKER_PUBLIC_READONLY_PAT: ${{ secrets.DOCKER_PUBLIC_READONLY_PAT }}

  appimage:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: test
      run: echo 'hello'

  staticbuild:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: test
      run: echo 'hello'

  slack-workflow-status:
    if: ${{ !success() }}
    name: Post Workflow Status To Slack
    needs:
      - test
      - appimage
      - staticbuild
    runs-on: ubuntu-latest
    permissions:
      actions: 'read'
    steps:
    - name: test
      run: echo 'hello'
