name: Pull Request Update

concurrency: 
  group: pullrequest-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  pull_request:
    branches: [ 'main' ]
    types: [ 'labeled', 'opened', 'reopened', 'synchronize' ]

# To test workflow updates you need to work in a branch directly on viamrobotics/rdk
# and tag your working branch instead of @main in any viamrobotics/rdk "uses" below.
# Don't forget to tag back to @main before merge.

jobs:
  test:
    uses: viamrobotics/rdk/.github/workflows/test.yml@testing4
    secrets:
      REPO_READ_TOKEN: ${{ secrets.REPO_READ_TOKEN }}
      GIT_ACCESS_TOKEN: ${{ secrets.GIT_ACCESS_TOKEN }}

  # This lets people add an "appimage" tag to have appimages built for the PR
  appimage:
    needs: test
    if: contains(github.event.pull_request.labels.*.name, 'appimage')
    uses: viamrobotics/rdk/.github/workflows/appimage.yml@testing4
    secrets:
      GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
      REPO_READ_TOKEN: ${{ secrets.REPO_READ_TOKEN }}
      GIT_ACCESS_TOKEN: ${{ secrets.GIT_ACCESS_TOKEN }}
