name: Pull Request Update

concurrency: 
  group: pullrequest-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  pull_request:
    branches: [ 'main' ]
    types: [ 'labeled', 'opened', 'reopened', 'synchronize' ]

# To test workflow updates you need to work in a branch directly on viamrobotics/rdk
# and tag your working branch instead of @main in any viamrobotics/rdk "uses" below.
# Don't forget to tag back to @main before merge.

jobs:
  test:
    uses: viamrobotics/rdk/.github/workflows/test.yml@main
    secrets:
      ARTIFACT_READ_ONLY_GCP_CREDENTIALS: ${{ secrets.ARTIFACT_READ_ONLY_GCP_CREDENTIALS }}
      MONGODB_TEST_OUTPUT_URI: ${{ secrets.MONGODB_TEST_OUTPUT_URI }}

  # This lets people add an "appimage" tag to have appimages built for the PR
  appimage:
    needs: test
    if: contains(github.event.pull_request.labels.*.name, 'appimage')
    uses: viamrobotics/rdk/.github/workflows/appimage.yml@main
    secrets:
      GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}

  eslint:
    # Ignore adding a new label not Deploy
    if: contains(fromJson('["opened", "synchronize", "reopened"]'), github.event.action)
    name: ESLint
    timeout-minutes: 5
    runs-on: [self-hosted, x64]
    container:
      image: ghcr.io/viamrobotics/canon:amd64-cache
      options: --platform linux/amd64
    steps:
    - uses: actions/checkout@v2
    - name: Install modules & generate protos
      run: make buf-web
    - name: Run ESLint
      run: make lint-web

  typecheck:
    # Ignore adding a new label not Deploy
    if: contains(fromJson('["opened", "synchronize", "reopened"]'), github.event.action)
    name: Typescript
    timeout-minutes: 5
    runs-on: [self-hosted, x64]
    container:
      image: ghcr.io/viamrobotics/canon:amd64-cache
      options: --platform linux/amd64
    steps:
    - uses: actions/checkout@v2
    - name: Install modules & generate protos
      run: make buf-web
    - name: Run Typecheck
      run: make typecheck-web
