name: Trigger Networking Tests in sdk-integration-tests

on:
    workflow_call:
    workflow_dispatch:

jobs:
    run-networking-tests:
        name: Trigger Networking Tests Workflow
        runs-on: ubuntu-latest
        steps:
        - name: Trigger Workflow
          run: |
            curl -X POST \
            -H "Authorization: token ${{ secrets.REPO_READ_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/viamrobotics/sdk-integration-tests/dispatches \
            -d '{"event_type":"new_rc_branch"}'
